### ISSUE TITLE
기능추가 의견 드립니다

### ISSUE THREAD

**Issue by dev-salteed** [Soobak123/MahjongPointer#1]
안녕하세요! 디시인사이드에서 보고 해당 프로그램 잘 사용하고 있는 사용자 입니다.
점수계산에 대한 요소가 모두 잘 포함되어 있어 지인들과 편하게 사용하고 있습니다. 갤럭시 폴드로 사용하니 좋더라구요 ㅎㅎ
사용하다보니 추가가 되면 어떨까.. 하는 기능들이 있어 제안드립니다.
1. 상태 저장기능.
 - 새로고침이나 재실행 되면 이전 상태를 불러오지 못해 게임 진행에 큰 영향을 받는 상황들이 발생했습니다. cookie 나 localstorage 사용 인터페이스를 만들어 webGL 에서의 상태 저장/불러오기를 보완 할 수 있을 것 같습니다. 추가로 음성과 같은 설정을 임시 저장 하는데에도 사용 할 수 있겠네요! 더 나중을 본다면,, 히스토리 관리도 가능 하겠네요.
2. 주사위 기능. 
 - 해당 기능이 추가되면 마작의 콤파스를 완전히 대체 할 수 있을 것이라 생각합니다!

감사합니다! 혹시나 제가 지원 해 드릴 사항이 있다면 말씀해주세요!

**Comment by Soobak123** [comment]
의견 감사드립니다. 해당 의견은 시간 여유가 될 때 빠르게 추가해보도록 노력해보겠습니다.
